### ISSUE TITLE
JSON security comment delimiters 

### ISSUE THREAD

**Issue by s1m3n** [tsenart/sight#21]
Some servers return JSON responses wrapped in security comment delimiters for security reasons. This would be an example of such a JSON string:
/*-secure- { "success": "true", "profile": { "id": "23r23rh54", "attributes": { "email":[ "email@example.com"], "companyName":[ "google"]} } } */

It would be great if sight could interpret these delimiters and properly format the JSON response inside them.

**Comment by xegea** [comment]
You should always set security comment delimiters (/*-secure-\n...*/) around sensitive JSON or JavaScript data to prevent Hijacking.
