### ISSUE TITLE
Incorrectly highlighting HTML files.

### ISSUE THREAD

**Issue by cjwelborn** [tsenart/sight#57]
Sight is interfering with local HTML files. It switches the background color and text style instead of letting the browser decide. We need an option to filter file extensions.

This is with Sight enabled:
![image](https://cloud.githubusercontent.com/assets/3335984/6471094/e108a890-c1ad-11e4-9166-ef4a6dc4a054.png)

This is what it should do (Sight disabled):
![image](https://cloud.githubusercontent.com/assets/3335984/6471105/f6f1711e-c1ad-11e4-8da7-16ff94bfb764.png)

**Comment by cjwelborn** [comment]
For now I've created a local copy of Sight (with no intent to publish) that doesn't do anything for 'htm' and 'html' files.

**Comment by tsenart** [comment]
@cjwelborn: I'd be glad to accept contributions that would fix this problem. :-)

**Comment by cjwelborn** [comment]
I know, I don't like filing issues without a pull request to go with them. When I'm busy I figure its better to at least know about the issue. Anyway, I'll see if I can look into it. Maybe filtering file extensions isn't the way to go, but instead just make sure Sight only highlights HTML when 'view source' is being used. I'll see what I can find.

**Comment by cjwelborn** [comment]
I made PR #58 to workaround this problem.
