### ISSUE TITLE
Error on option.html

### ISSUE THREAD

**Issue by idiotWu** [tsenart/sight#61]
When I try to change preference at option page, all settings will be set to default while the page is reloaded. Looked into developer tools and I found this:

![error](https://cloud.githubusercontent.com/assets/6022672/7553854/5f9aa804-f73f-11e4-91a3-a996f20f18d9.jpg)

So, is there something wrong in https://github.com/tsenart/sight/blob/master/js/options.js#L36 ?

**Comment by tsenart** [comment]
Thanks for reporting. This is a very easy fix. I just have to replace
`identity` with `id` like the other options before that one. If you want,
you can submit a PR for that and I'll take care of releasing in a few hours.

On Sunday, May 10, 2015, Dolphin Wood <notifications@github.com> wrote:

> When I try to change preference at option page, all settings will be set
> to default while the page is reloaded. Looked into developer tools and I
> found this:
>
> [image: error]
> <https://cloud.githubusercontent.com/assets/6022672/7553854/5f9aa804-f73f-11e4-91a3-a996f20f18d9.jpg>
>
> So, is there something wrong in
> https://github.com/tsenart/sight/blob/master/js/options.js#L36 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tsenart/sight/issues/61>.
>


-- 
Sent from Gmail Mobile

**Comment by idiotWu** [comment]
I've made PR #62 to fix this :)
