### ISSUE TITLE
Horizontal scroll on bottom code instead on bottom of browser view

### ISSUE THREAD

**Issue by bentinata** [tsenart/sight#68]
Happens on long and wide code.
Can you give insight on building this?

Thanks.

**Comment by tsenart** [comment]
Please provide more information. I can't really work with what you gave me.

**Comment by bentinata** [comment]
Is this intended? Because it feels awkward, since plain browser would show wrapped text with vertical scrollbar. And code-editor would display scrollbar at the edges of page.  
Example screenshot of https://code.jquery.com/jquery-2.1.4.min.js. ![https://code.jquery.com/jquery-2.1.4.min.js](https://cloud.githubusercontent.com/assets/3183661/9083017/19fd0c8c-3b92-11e5-8978-f3a163f456be.png)
Notice how the scrollbar is not at the bottom of the div.

Also on longer and wider code http://www.google-analytics.com/analytics.js.
![http://www.google-analytics.com/analytics.js](https://cloud.githubusercontent.com/assets/3183661/9083238/5d3678d4-3b93-11e5-8153-11ac2b3e4bcc.png)
Horizontal scrollbar is inside the element with vertical scrollbar.

Suggested changes is just use `overflow: visible` on `<pre>` element. And use `overflow: auto` on `<body>` element.

Thanks. :)

**Comment by tsenart** [comment]
That doesn't look right. Contributions welcome!

**Comment by tsenart** [comment]
Closed by #75.
