### ISSUE TITLE
Add all of highlight.js supported languages

### ISSUE THREAD

**Issue by sdecima** [tsenart/sight#70]
I tried to highlight files of Apache conf files, and it didn't work, not even with #ft=apache, and I see in the code that it does not include all languages supported by highlight.js (that are already included in /js/languages in the repository).
I can take care of adding the new ones to the LANG_EXT_MAP list if that's helpful.

**Comment by tsenart** [comment]
Yep, open a small, targeted PR for that and I'll review it!

**Comment by icholy** [comment]
This looks like it can be closed too.

**Comment by sdecima** [comment]
Thanks @icholy I forgot to close it after my PR.
