### ISSUE TITLE
Add Typescript

### ISSUE THREAD

**Issue by leocaseiro** [tsenart/sight#77]
Hi, Any chances to add `.ts` files?

Should I send you a PR?

Thanks

**Comment by tsenart** [comment]
Yes, please open a PR.

**Comment by tsenart** [comment]
Or perhaps see if #70 isn't implemented before...

**Comment by icholy** [comment]
#83 adds support for typescript. This issue can be closed.

**Comment by leocaseiro** [comment]
Thanks @icholy
