### ISSUE TITLE
latest version 1.19.0 can't work on local files

### ISSUE THREAD

**Issue by 4disland** [tsenart/sight#84]
I had the need to view local source file in chrome, so I dig on google and found this good extension.
I noticed that someone before had opened issues [related,](https://github.com/tsenart/sight/issues/72) but I can't find where to allow this extension to access file, can you help me with this?
thanks.

**Comment by tsenart** [comment]
![screen shot 2016-08-26 at 19 32 41](https://cloud.githubusercontent.com/assets/67471/18016477/81ce1794-6bc4-11e6-9954-2c83b4658183.png)
