### ISSUE TITLE
firefox ports

### ISSUE THREAD

**Issue by staabm** [tsenart/sight#86]
any known ports for firefox which could be documented in the readme?

**Comment by tsenart** [comment]
Not that I'm aware. If you find something similar, please open a PR.

**Comment by callodacity** [comment]
@staabm @tsenart I've just released a firefox version https://addons.mozilla.org/en-US/firefox/addon/colorcode/

It isn't exactly a port, but it is inspired by this addon (github: https://github.com/callodacity/colorcode).
